const primary = "#E8401C";
const darkNavy = "#1A1F2E";

export default {
  primary,
  primaryLight: "#FF6B45",
  primaryDark: "#C4320F",
  dark: darkNavy,
  darkSecondary: "#252B3B",
  text: "#1A1F2E",
  textSecondary: "#6B7280",
  textTertiary: "#9CA3AF",
  background: "#F4F5F8",
  card: "#FFFFFF",
  border: "#E5E7EB",
  success: "#10B981",
  successLight: "#D1FAE5",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  danger: "#EF4444",
  dangerLight: "#FEE2E2",
  info: "#3B82F6",
  infoLight: "#DBEAFE",
  purple: "#8B5CF6",
  purpleLight: "#EDE9FE",
  teal: "#0D9488",
  tealLight: "#CCFBF1",
  white: "#FFFFFF",
  tabIconDefault: "#9CA3AF",
  tabIconSelected: primary,
};
